language: php

php:
  - "7.1"
  - "7.2"

before_script:
  - composer install

after_script:
  - php vendor/bin/php-coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

dist: trusty

notifications:
  email:
    - sam@badcow.co